apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  type: NodePort
  ports:
  - nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground
